<script type="text/javascript">
      var _A = "NOMINA";
	var menuItems = [
		["Gesti&oacute;n", , , , , , "0", , , , , ],
			["|Empleados", "<?=$_PARAMETRO["PATHSIA"]?>empleados/gehen.php?anz=empleados_lista&filtrar=default&concepto=01-0001&_APLICACION="+_A, , , , d['01-0001'], , , , , , ],
			
		["Procesos", , , , , , "0", , , , , ],
			["|Asignación de Conceptos", , , , , , , , , , , ],
				["||Temporales", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_conceptos_temporales&filtrar=default&concepto=05-0001&limit=0&_APLICACION="+_A, , , , d['05-0001'], , , , , , ],						
				["||Permanentes", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_conceptos_permanentes&filtrar=default&concepto=05-0002&limit=0&_APLICACION="+_A, , , , d['05-0002'], , , , , , ],                  				

			["|Ajuste Salarial", , , , , , , , , , , ],
				["||Ajuste x Grado Salarial", , , , , , , , , , , ],
					["|||Listar Ajustes", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_ajuste_salarial_lista&filtrar=default&lista=todos&concepto=05-0010&_APLICACION="+_A, , , , d['05-0010'], , , , , , ],							
					["|||Aprobar Ajustes", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_ajuste_salarial_lista&filtrar=default&lista=aprobar&concepto=05-0014&_APLICACION="+_A, , , , d['05-0014'], , , , , , ],                  					
				["||Ajuste x Empleados", , , , , , , , , , , ],
					["|||Listar Ajustes", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_ajuste_salarial_emp_lista&filtrar=default&lista=todos&concepto=05-0017&_APLICACION="+_A, , , , d['05-0017'], , , , , , ],							
					["|||Aprobar Ajustes", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_ajuste_salarial_emp_lista&filtrar=default&lista=aprobar&concepto=05-0018&_APLICACION="+_A, , , , d['05-0018'], , , , , , ],                  				

			["|Liquidaciones", , , , , , , , , , , ],
				["||Control de Prestaciones", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_prestaciones_control&filtrar=default&concepto=05-0016&limit=0&_APLICACION="+_A, , , , d['05-0016'], , , , , , ],                  				

			["|Fideicomiso", , , , , , , , , , , ],
				["||Acumulados del Fideicomiso", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_fideicomiso_acumulado_lista&filtrar=default&concepto=05-0007&limit=0&_APLICACION="+_A, , , , d['05-0007'], , , , , , ],
                ["||Depósitos de Antiguedad", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_fideicomiso_actualizar_lista&filtrar=default&concepto=05-0008&_APLICACION="+_A, , , , d['05-0008'], , , , , , ],
                ["||Actualizar Intereses", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_fideicomiso_intereses_lista&filtrar=default&concepto=05-0020&_APLICACION="+_A, , , , d['05-0020'], , , , , , ],
				["||Cálculo de Fideicomiso", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_fideicomiso_procesar_calculo&filtrar=default&concepto=05-0015&_APLICACION="+_A, , , , d['05-0015'], , , , , , ],                  					

			["|Pre Nómina", , , , , , , , , , , ],
				["||Control de Procesos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_prenomina_procesos_lista&filtrar=default&lista=todos&concepto=05-0011&_APLICACION="+_A, , , , d['05-0011'], , , , , , ],
				["||Ejecución de Procesos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_prenomina_ejecucion&filtrar=default&concepto=05-0012&_APLICACION="+_A, , , , d['05-0012'], , , , , , ],                  					

			["|Nómina", , , , , , , , , , , ],
				["||Control de Procesos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_procesos_control_lista&filtrar=default&lista=todos&concepto=05-0004&_APLICACION="+_A, , , , d['05-0004'], , , , , , ],
				["||Aprobación de Procesos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_procesos_control_lista&filtrar=default&lista=aprobar&concepto=05-0005&_APLICACION="+_A, , , , d['05-0005'], , , , , , ],
				["||-",, , , , , , , , , , ],
				["||-",, , , , , , , , , , ],
				["||Ejecución de Procesos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_procesos_control_ejecucion&filtrar=default&concepto=05-0006&_APLICACION="+_A, , , , d['05-0006'], , , , , , ],
				["||-",, , , , , , , , , , ],
				["||-",, , , , , , , , , , ],
				["||Complemento de Sueldos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_complemento_sueldos_lista&filtrar=default&lista=todos&concepto=05-0026&_APLICACION="+_A, , , , d['05-0026'], , , , , , ],
				//["||Modificar Payroll", "<?=$_PARAMETRO["PATHSIA"]?>nomina/modificar_payroll.php?&filtrar=default&concepto=05-0009&_APLICACION="+_A, , , , d['05-0009'], , , , , , ],                  					

			["|Proyección Gastos de Personal", , , , , , , , , , , ],
				["||Escalas Salariales", , , , , , , , , , , ],
					["|||Ajustes por Grado Salarial", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_proyajustegrado_lista&filtrar=default&concepto=05-0020&_APLICACION="+_A, , , , d['05-0020'], , , , , , ],
					["|||Ajustes por Empleado", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_proyajusteempleado_lista&filtrar=default&concepto=05-0021&_APLICACION="+_A, , , , d['05-0021'], , , , , , ],

				["||Planificación de Recursos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_proyrecursos_lista&filtrar=default&lista=todos&concepto=05-0022&_APLICACION="+_A, , , , d['05-0022'], , , , , , ],

				["||Definición de Parámetros", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_proyparametro_lista&filtrar=default&lista=todos&concepto=05-0023&_APLICACION="+_A, , , , d['05-0023'], , , , , , ],

				["||Proyección de Gastos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_proyejecucion_lista&filtrar=default&lista=todos&concepto=05-0024&_APLICACION="+_A, , , , d['05-0024'], , , , , , ],

				["||Proyección Presupuestaria", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_proypresupuestaria_lista&filtrar=default&lista=listar&concepto=05-0025&_APLICACION="+_A, , , , d['05-0025'], , , , , , ],

			["|-",, , , , , , , , , , ],
			["|-",, , , , , , , , , , ],
			["|Interfase Cuentas por Pagar", , , , , , , , , , , ],
			    ["||Nómina", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_interfase_cuentas_por_pagar&filtrar=default&concepto=05-0013&_APLICACION="+_A, , , , d['05-0013'], , , , , , ],
			    ["||Bono de Alimentación", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_interfase_cuentas_por_pagar_bono&filtrar=default&concepto=05-0027&_APLICACION="+_A, , , , d['05-0027'], , , , , , ],
        
		["Reportes", , , , , , "0", , , , , ],
			["|Empleados", , , , , , , , , , , ],
				["||Empleados", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=reporte_empleados&filtrar=default&concepto=02-0004&limit=0&_APLICACION="+_A, , , , d['02-0004'], , , , , , ],						
				["||Carga Familiar", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=reporte_carga_familiar&filtrar=default&concepto=02-0001&limit=0&_APLICACION="+_A, , , , d['02-0001'], , , , , , ],						
				["||Constancias de Trabajo", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=reporte_constancia&filtrar=default&concepto=02-0032&limit=0&_APLICACION="+_A, , , , d['02-0032'], , , , , , ],
				["||-",, , , , , , , , , , ],
				["||-",, , , , , , , , , , ],						
				["||Aniversarios", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=reporte_aniversarios&filtrar=default&concepto=02-0003&limit=0&_APLICACION="+_A, , , , d['02-0003'], , , , , , ],						
				["||Cumpleaños", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=reporte_cumpleanios&filtrar=default&concepto=02-0002&limit=0&_APLICACION="+_A, , , , d['02-0002'], , , , , , ],                  					
			["|Fideicomiso", , , , , , , , , , , ],
				["||Calculo de Fideicomiso", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_fideicomiso_calculo_pdf_filtro&filtrar=default&concepto=02-0030&_APLICACION="+_A, , , , d['02-0030'], , , , , , ],						
				["||Garantía de Prestaciones", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_prestaciones_garantia_reporte_filtro&concepto=02-0036&_APLICACION="+_A, , , , d['02-0036'], , , , , , ],                                                
                  ["|Liquidaciones", , , , , , , , , , , ],
                        ["||Control de Prestaciones", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_liquidaciones_lista_filtro&filtrar=default&concepto=02-0037&_APLICACION="+_A, , , , d['02-0037'], , , , , , ],                  					
			["|Nómina", , , , , , , , , , , ],
				// ["||Resumen de Conceptos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_resumen_conceptos_filtro&concepto=02-0005&_APLICACION="+_A, , , , d['02-0005'], , , , , , ],
				// ["||Resumen de Conceptos por Proceso", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_resumen_conceptos_proceso_filtro&concepto=02-0020&_APLICACION="+_A, , , , d['02-0020'], , , , , , ],
				["||Resumen de Conceptos por Partidas", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_resumen_conceptos_partidas_filtro&concepto=02-0026&_APLICACION="+_A, , , , d['02-0026'], , , , , , ],
				["||Resumen por Categorias Programáticas", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_resumen_categorias_filtro&concepto=02-0040&_APLICACION="+_A, , , , d['02-0040'], , , , , , ],
				["||Relación de Nómina", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_relacion_nomina_filtro&concepto=02-0006&_APLICACION="+_A, , , , d['02-0006'], , , , , , ],
				["||Payroll de Pago", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_payroll_pago&filtrar=default&concepto=02-0035&limit=0&_APLICACION="+_A, , , , d['02-0035'], , , , , , ],
				["||Payroll de Pago x Periodo", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_payroll_pago_periodo&filtrar=default&concepto=02-0013&limit=0&_APLICACION="+_A, , , , d['02-0013'], , , , , , ],
				["||Nómina de Trabajadores", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reportes_nomina.php?concepto=02-0012&_APLICACION="+_A, , , , d['02-0012'], , , , , , ],
				["||Resumen Detallado de Conceptos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_resumen_detallado_conceptos_filtro&concepto=02-0017&_APLICACION="+_A, , , , d['02-0017'], , , , , , ],
				["||-",, , , , , , , , , , ],
				["||-",, , , , , , , , , , ],
				["||Generar TXT Nómina", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reportes_generar_txt.php?concepto=02-0022&_APLICACION="+_A, , , , d['02-0022'], , , , , , ],
				["||-",, , , , , , , , , , ],
				["||-",, , , , , , , , , , ],
				["||Reporte de Auditoria General", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reportes_auditoria_general.php?concepto=02-0018&_APLICACION="+_A, , , , d['02-0018'], , , , , , ],						
				["||Reporte de Auditoria Detallado", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reportes_auditoria_detallado.php?concepto=02-0019&_APLICACION="+_A, , , , d['02-0019'], , , , , , ],
				["||-",, , , , , , , , , , ],
				["||-",, , , , , , , , , , ],
				["||Relación de Ingresos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reportes_relacion_ingresos.php?concepto=02-0023&_APLICACION="+_A, , , , d['02-0023'], , , , , , ],
				["||Conceptos por Listado", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reportes_conceptos_listado.php?concepto=02-0024&_APLICACION="+_A, , , , d['02-0024'], , , , , , ],						
				["||Conceptos por Listado Anual", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reportes_conceptos_listado_anual.php?concepto=02-0027&_APLICACION="+_A, , , , d['02-0027'], , , , , , ],						
				["||Listado por Proceso", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reportes_procesos_listado.php?concepto=02-0025&_APLICACION="+_A, , , , d['02-0025'], , , , , , ],
				["||Reporte por Conceptos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reporte_conceptos.php?concepto=02-0028&_APLICACION="+_A, , , , d['02-0028'], , , , , , ],
				["||Conceptos por Periodo", "<?=$_PARAMETRO["PATHSIA"]?>nomina/reporte_conceptos_periodo.php?concepto=02-0029&_APLICACION="+_A, , , , d['02-0029'], , , , , , ],
				["||Registro de Asignación de Cargos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_asignacion_cargo_filtro&concepto=02-0037&_APLICACION="+_A, , , , d['02-0037'], , , , , , ],
				["||-",, , , , , , , , , , ],
				["||-",, , , , , , , , , , ],
				["||Relación de Sueldos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_relacion_sueldos&concepto=02-0041", , , , d['02-0041'], , , , , , ],
			["|Retenciones y Aportes", , , , , , , , , , , ],
				["||Retenciones de Impuesto Sobre la Renta", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_islr_filtro&concepto=02-0007&_APLICACION="+_A, , , , d['02-0007'], , , , , , ],
				["||Retenciones Vivienda y Hábitat", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_vivienda_filtro2&concepto=02-0008&_APLICACION="+_A, , , , d['02-0008'], , , , , , ],
				["||Retenciones Jubilación y Pensión", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_jubilacion_pension_filtro&concepto=02-0009&_APLICACION="+_A, , , , d['02-0009'], , , , , , ],
				["||Retenciones Seguro Social Obligatorio", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_sso_filtro&concepto=02-0010&_APLICACION="+_A, , , , d['02-0010'], , , , , , ],
				["||Retenciones Paro Forzoso", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_paro_forzoso_filtro&concepto=02-0011&_APLICACION="+_A, , , , d['02-0011'], , , , , , ],
				["||Retenciones FUNDECEDA", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_fundeceda_filtro&concepto=02-0014&_APLICACION="+_A, , , , d['02-0014'], , , , , , ],
				["||Retenciones Medida Preventiva de Embargo", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_embargo_filtro&concepto=02-0015&_APLICACION="+_A, , , , d['02-0015'], , , , , , ],
				["||Retenciones Embargo Prima por Hijos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_prima_hijos_filtro&concepto=02-0016&_APLICACION="+_A, , , , d['02-0016'], , , , , , ],
                        ["||Otras Retenciones", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_retenciones_filtro&concepto=02-0021&_APLICACION="+_A, , , , d['02-0021'], , , , , , ],
                        ["||Comprobante de Retención AR-C", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_reporte_comprobante_arc_filtro&filtrar=default&lista=todos&concepto=02-0037", , , , d['02-0037'], , , , , , ],                  					
			["|Vacaciones", , , , , , , , , , , ],
				["||Pago de Vacaciones", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_vacaciones_pago_lista&filtrar=default&concepto=02-0031&_APLICACION="+_A, , , , d['02-0031'], , , , , , ],

			["|Proyección de Gastos", , , , , , , , , , , ],
				["||Distribución Ppto. x Categoria Programaticas", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_proyecciongastos&filtrar=default&concepto=02-0038&_APLICACION="+_A, , , , d['02-0038'], , , , , , ],
				["||Registro de Información de Cargos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_proyeccioncargos&filtrar=default&concepto=02-0039&_APLICACION="+_A, , , , d['02-0039'], , , , , , ],

		["Maestros", , , , , , "0", , , , , ],
			["|Del Sistema SIA", , , , , , , , , , , ],
				["||Propios del Sistema", , , , , , , , , , , ],
					["|||Aplicaciones", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=aplicaciones_lista&filtrar=default&concepto=03-0002&_APLICACION="+_A, , , , d['03-0002'], , , , , , ],
					["|||Par&aacute;metros", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=parametros_lista&filtrar=default&concepto=03-0003&_APLICACION="+_A, , , , d['03-0003'], , , , , , ],
				["||Relacionados a Personas", , , , , , , , , , , ],
					["|||Personas", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=personas_lista&filtrar=default&concepto=03-0001&_APLICACION="+_A, , , , d['03-0001'], , , , , , ],
					["|||Organismos", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=organismos_lista&filtrar=default&concepto=03-0010&_APLICACION="+_A, , , , d['03-0010'], , , , , , ],
					["|||Dependencias", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=dependencias_lista&filtrar=default&concepto=03-0011&_APLICACION="+_A, , , , d['03-0011'], , , , , , ],
				["||Relacionados a Contabilidad", , , , , , , , , , , ],
					["|||Plan de Cuentas", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=plan_cuentas_lista&filtrar=default&concepto=03-0045&_APLICACION="+_A, , , , d['03-0045'], , , , , , ],
                              ["|||Plan de Cuentas (Pub. 20)", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=plan_cuentas_pub20&filtrar=default&concepto=03-0061", , , , d['03-0061'], , , , , , ],
					["|||Grupos de Centros de Costos", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=grupo_centro_costos_lista&filtrar=default&concepto=03-0046&_APLICACION="+_A, , , , d['03-0046'], , , , , , ],
					["|||Centros de Costos", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=centro_costos_lista&filtrar=default&concepto=03-0047&_APLICACION="+_A, , , , d['03-0047'], , , , , , ],
				["||Relacionados a Presupuesto", , , , , , , , , , , ],
					["|||Tipos de Cuenta", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=tipo_cuenta_lista&filtrar=default&concepto=03-0056&_APLICACION="+_A, , , , d['03-00563'], , , , , , ],
					["|||Clasificador Presupuestario", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=clasificador_presupuestario_lista&filtrar=default&concepto=03-0057&_APLICACION="+_A, , , , d['03-0057'], , , , , , ],
				["||Otros Maestros", , , , , , , , , , , ],
					["|||Paises", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=paises_lista&filtrar=default&concepto=03-0004&_APLICACION="+_A, , , , d['03-0004'], , , , , , ],
					["|||Estados", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=estados_lista&filtrar=default&concepto=03-0005&_APLICACION="+_A, , , , d['03-0005'], , , , , , ],
					["|||Municipios", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=municipios_lista&filtrar=default&concepto=03-0006&_APLICACION="+_A, , , , d['03-0006'], , , , , , ],
					["|||Ciudades", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=ciudades_lista&filtrar=default&concepto=03-0007&_APLICACION="+_A, , , , d['03-0007'], , , , , , ],
					["|||Parroquias", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=parroquias_lista&filtrar=default&concepto=03-0060&_APLICACION="+_A, , , , d['03-0060'], , , , , , ],
					["|||Comunidades", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=comunidades_lista&filtrar=default&concepto=03-0062&_APLICACION="+_A, , , , d['03-0062'], , , , , , ],
					["|||Localidades", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=localidades_lista&filtrar=default&concepto=03-0064&_APLICACION="+_A, , , , d['03-0064'], , , , , , ],
					["|||Tipos de Pago", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=tipos_pago_lista&filtrar=default&concepto=03-0008&_APLICACION="+_A, , , , d['03-0008'], , , , , , ],
					["|||Bancos", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=bancos_lista&filtrar=default&concepto=03-0009&_APLICACION="+_A, , , , d['03-0009'], , , , , , ],
					["|||Unidad Tributaria", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=unidad_tributaria_lista&filtrar=default&concepto=03-0058&_APLICACION="+_A, , , , d['03-0058'], , , , , , ],                  				
			["|Organizaci&oacute;n", , , , , , , , , , , ],
				["||Tipos de Cargo", "<?=$_PARAMETRO["PATHSIA"]?>organizacion/gehen.php?anz=tipo_cargo_lista&filtrar=default&concepto=03-0014&_APLICACION="+_A, , , , d['03-0014'], , , , , , ],
				["||Nivel de Tipos de Cargo", "<?=$_PARAMETRO["PATHSIA"]?>organizacion/gehen.php?anz=nivel_tipo_cargo_lista&filtrar=default&concepto=03-0015&_APLICACION="+_A, , , , d['03-0015'], , , , , , ],
				["||Grupo Ocupacional", "<?=$_PARAMETRO["PATHSIA"]?>organizacion/gehen.php?anz=grupo_ocupacional_lista&filtrar=default&concepto=03-0012&_APLICACION="+_A, , , , d['03-0012'], , , , , , ],
				["||Serie Ocupacional", "<?=$_PARAMETRO["PATHSIA"]?>organizacion/gehen.php?anz=serie_ocupacional_lista&filtrar=default&concepto=03-0013&_APLICACION="+_A, , , , d['03-0013'], , , , , , ],
				["||Grado Salarial", "<?=$_PARAMETRO["PATHSIA"]?>organizacion/gehen.php?anz=nivelsalarial_lista&filtrar=default&concepto=03-0044&_APLICACION="+_A, , , , d['03-0044'], , , , , , ],
				["||Cargos", "<?=$_PARAMETRO["PATHSIA"]?>organizacion/gehen.php?anz=cargos_lista&filtrar=default&concepto=03-0016&_APLICACION="+_A, , , , d['03-0016'], , , , , , ],
			["|Relaciones Laborales", , , , , , , , , , , ],
				["||Tipos de Trabajador", "<?=$_PARAMETRO["PATHSIA"]?>relaciones_laborales/gehen.php?anz=tipo_trabajador_lista&filtrar=default&concepto=03-0022&_APLICACION="+_A, , , , d['03-0022'], , , , , , ],
				["||Tipos de N&oacute;mina", "<?=$_PARAMETRO["PATHSIA"]?>relaciones_laborales/gehen.php?anz=tipo_nomina_lista&filtrar=default&concepto=03-0023&_APLICACION="+_A, , , , d['03-0023'], , , , , , ],
				["||Perfiles de Nómina", "<?=$_PARAMETRO["PATHSIA"]?>relaciones_laborales/gehen.php?anz=perfil_nomina_lista&filtrar=default&concepto=03-0024&_APLICACION="+_A, , , , d['03-0024'], , , , , , ],
				["||Tipos de Contrato", "<?=$_PARAMETRO["PATHSIA"]?>relaciones_laborales/gehen.php?anz=tipo_contrato_lista&filtrar=default&concepto=03-0025&_APLICACION="+_A, , , , d['03-0025'], , , , , , ],
				["||Formatos de Contrato", "<?=$_PARAMETRO["PATHSIA"]?>relaciones_laborales/gehen.php?anz=formato_contrato_lista&filtrar=default&concepto=03-0026&_APLICACION="+_A, , , , d['03-0026'], , , , , , ],
				["||Motivos de Cese", "<?=$_PARAMETRO["PATHSIA"]?>relaciones_laborales/gehen.php?anz=motivo_cese_lista&filtrar=default&concepto=03-0027&_APLICACION="+_A, , , , d['03-0027'], , , , , , ],
				["||Horario Laboral", "<?=$_PARAMETRO["PATHSIA"]?>relaciones_laborales/gehen.php?anz=horario_laboral_lista&filtrar=default&concepto=03-0059&_APLICACION="+_A, , , , d['03-0059'], , , , , , ],
				["||Cuadrillas", "<?=$_PARAMETRO["PATHSIA"]?>relaciones_laborales/gehen.php?anz=cuadrillas_lista&filtrar=default&concepto=03-0063&_APLICACION="+_A, , , , d['03-0063'], , , , , , ],

			["|N&oacute;minas", , , , , , , , , , , ],
				["||Tipos de Proceso", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_tipo_proceso_lista&filtrar=default&concepto=03-0041&_APLICACION="+_A, , , , d['03-0041'], , , , , , ],                  					
				["||Conceptos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_conceptos_lista&filtrar=default&concepto=03-0043&_APLICACION="+_A, , , , d['03-0043'], , , , , , ],                  					
				["||Perfil de Conceptos", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_conceptos_perfil_lista&filtrar=default&concepto=03-0055&_APLICACION="+_A, , , , d['03-0055'], , , , , , ],                  				
			["|Otros", , , , , , , , , , , ],
				["||Miscel&aacute;neos", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=miscelaneos_lista&filtrar=default&concepto=03-0040&_APLICACION="+_A, , , , d['03-0040'], , , , , , ],
                        ["||Tasas de Interes", "<?=$_PARAMETRO["PATHSIA"]?>nomina/gehen.php?anz=pr_tasa_interes_lista&filtrar=default&concepto=03-0048&_APLICACION="+_A, , , , d['03-0048'], , , , , , ],
				["||Tabla de Sueldos Mínimos", "<?=$_PARAMETRO["PATHSIA"]?>rh/gehen.php?anz=rh_sueldos_minimos_lista&filtrar=default&concepto=03-0054&_APLICACION="+_A, , , , d['03-0054'], , , , , , ],
			
		["Admin.", , , , , , "0", , , , , ],
			["|Seguridad", , , , , , , , , , , ],
				["||Maesto de Usuarios", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=usuarios_lista&lista=usuarios&filtrar=default&concepto=04-0001&_APLICACION="+_A, , , , d['04-0001'], , , , , , ],
				["||Dar Autorizaciones a Usuarios", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=usuarios_lista&lista=autorizaciones&filtrar=default&concepto=04-0002&_APLICACION="+_A, , , , d['04-0002'], , , , , , ],
			["|Seguridad Alterna", , , , , , , , , , , ],
				["||Dar Autorizaciones a Usuarios", "<?=$_PARAMETRO["PATHSIA"]?>comunes/gehen.php?anz=usuarios_lista&lista=alterna&filtrar=default&concepto=04-0003&_APLICACION="+_A, , , , d['04-0003'], , , , , , ],
            ["|Generar Voucher de Nómina", "<?=$_PARAMETRO["PATHSIA"]?>nomina/voucher_nomina.php?concepto=04-0004&limit=0&filtrar=DEFAULT&_APLICACION="+_A, , , , d['04-0004'], , , , , , ],
	];
      dm_initFrame("frmSet", 0, 1, 0);
</script>