INSERT INTO lg_transaccion
					SET
						CodOrganismo = '0001',
						CodDocumento = 'NI',
						NroDocumento = '000001',
						CodTransaccion = 'IAI',
						FechaDocumento = '2018-01-06',
						Periodo = '2018-01',
						CodAlmacen = 'ALWABI',
						CodCentroCosto = '0003',
						CodDocumentoReferencia = 'AJ',
						NroDocumentoReferencia = '456',
						IngresadoPor = '000002',
						RecibidoPor = '',
						Comentarios = 'Comentarios',
						FlagManual = 'N',
						FlagPendiente = 'N',
						ReferenciaAnio = '2018',
						ReferenciaNroDocumento = '',
						DocumentoReferencia = '123',
						DocumentoReferenciaInterno = '',
						CodDependencia = '0002',
						Anio = '2018',
						Estado = 'PR',
						UltimoUsuario = 'KMILANO',
						UltimaFecha = NOW();

INSERT INTO lg_transacciondetalle
						SET
							CodOrganismo = '0001',
							CodDocumento = 'NI',
							NroDocumento = '000001',
							Secuencia = '1',
							CodItem = '0000000001',
							Descripcion = 'ACEITE DE SOYA DIANA 12X1 LT',
							CodUnidad = 'UNI',
							CantidadPedida = '123',
							CantidadRecibida = '123',
							PrecioUnit = '0',
							Total = '0',
							ReferenciaAnio = '2018',
							ReferenciaCodDocumento = 'AJ',
							ReferenciaNroDocumento = '456',
							ReferenciaSecuencia = '1',
							CodCentroCosto = '0003',
							Estado = 'PR',
							UltimoUsuario = 'KMILANO',
							UltimaFecha = NOW();

INSERT INTO lg_transacciondetalle
						SET
							CodOrganismo = '0001',
							CodDocumento = 'NI',
							NroDocumento = '000001',
							Secuencia = '2',
							CodItem = '0000000002',
							Descripcion = 'ACEITE DE SOYA ORIENTAL 12X1 LT',
							CodUnidad = 'UNI',
							CantidadPedida = '456',
							CantidadRecibida = '456',
							PrecioUnit = '0',
							Total = '0',
							ReferenciaAnio = '2018',
							ReferenciaCodDocumento = 'AJ',
							ReferenciaNroDocumento = '456',
							ReferenciaSecuencia = '2',
							CodCentroCosto = '0003',
							Estado = 'PR',
							UltimoUsuario = 'KMILANO',
							UltimaFecha = NOW();

